apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  releaseName: tailscale-operator
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: 1.80.x
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  valuesFrom:
    - kind: Secret
      name: secrets
      valuesKey: oauthClientId
      targetPath: oauth.clientId
    - kind: Secret
      name: secrets
      valuesKey: oauthClientSecret
      targetPath: oauth.clientSecret

