apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
spec:
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      containers:
        - name: immich-redis
          image: docker.io/redis:6.2-alpine
          ports:
            - containerPort: 6379
