apiVersion: v1
kind: Secret
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:AgN4oEyYB1i0r9P8isxc25CzTpo=,iv:2KHsVQ51BwBjvae7okCLNaEK4h4cxghdeckyDmHzQdI=,tag:1F/RzItKi5WLBuJ/nbuyMg==,type:str]
metadata:
    name: secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15cm9jgzm2w94fsf7kuk7cv68nmdgeha2wpynu5qrmmsdqsy45yaqdja4qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNXdSOWFjRjRjMXhia3lV
            L2U1bWMwQUNZb2RIUm8rMTc2K2l5d1N2MDNRCmNXWDN5WjZmN0hRNnhWV2haQllP
            QU8vcHJGSnJSMVlvMCtDMURBWVRUaUkKLS0tIEFXU0t6RVZDMnpRT3NqNXZJaUxY
            NjRvVVRmcGtZS3pKY2NvWTV0MWorZ3MKAKg5i9Qae1Pl1cmEGpBOraivs1XNTOt6
            gFC9eUXabOFI8ZZCp/0TRWM5RjtmnXkY7i4AWRTf9npChaWj/s+JcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T06:32:38Z"
    mac: ENC[AES256_GCM,data:HJbrredLUqNu7S9zV4g5B+3GQaFNrPEu62D1ms2li2B7/2lg/VBCTSV+vFiwmd9twmRxM1u4OIm5P6/7hX2/mZJ5H/QaJLI/SO6tfRBHmyNH86wsa2TVO+6EtG92i5zt7C7n1+nGfQ9bh2d0Yh9JPV5N3mwtlCXWQlzROEpXxYE=,iv:2gOrjzXoRs1n5dJh6WUjM+m5p4f8lj6ofXsNiaMBDHI=,tag:My62pJyAws5zGnabqUkVvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
