apiVersion: apps/v1
kind: Deployment
metadata:
  name: balacord
spec:
  selector:
    matchLabels:
      app: balacord
  template:
    metadata:
      labels:
        app: balacord
    spec:
      containers:
        - name: balacord
          image: ghcr.io/danielpower/balacord:main@sha256:0ae323f4183f1ec90f831f2a9108db6f55e70c0e35364e86e9519f37d5f19d10
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: balacord-postgres-app
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: balacord-postgres-app
                  key: password
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: balacord-postgres-app
                  key: host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: balacord-postgres-app
                  key: port
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: balacord-postgres-app
                  key: dbname
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
