apiVersion: apps/v1
kind: Deployment
metadata:
  name: balacord
spec:
  selector:
    matchLabels:
      app: balacord
  template:
    metadata:
      labels:
        app: balacord
    spec:
      containers:
        - name: balacord
          image: ghcr.io/danielpower/balacord:main@sha256:c7cef927762b075b373971f54b788a88b61bb25cdfc80720fdda8568f8ad8629
          envFrom:
            - secretRef:
                name: secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
