apiVersion: v1
kind: Secret
stringData:
    APP_NAME: ENC[AES256_GCM,data:UJz0yb9DWFQ=,iv:N6IrNNKOHA4LLOna1dtEjdddRHIncKtDwHbJ46uhOes=,tag:6P6c6LsPUiAaLH0aqkcQsw==,type:str]
    DISCORD_APPLICATION_ID: ENC[AES256_GCM,data:UfLGD2DHenZQr9TUkdjt8Nme1w==,iv:Gl9o21PLJEIo9ttEmWAk+TSjfIx2a3kV+Ov8axBrn9M=,tag:v6lTX7Lg84KFmDTmQGRLxA==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:8x3t7k3UfMiGsrnqW2BUMHKLKnrXBA+qrH/7SiI+qIUq0A2Fg+9HozSpuH5iYcldUiX+ByMNzi8yENy3eIaDg3jWClUnRD+t,iv:9KO6sndv6PyP82/4jjb3igC+rolxNqACGmnnPSJ3zgw=,tag:JlQBu/Ru6dbSoSTZAQpl4w==,type:str]
    LOKI_URL: ENC[AES256_GCM,data:VdHbaaVpAolpnYn2m9SslnNs05F2qL2eqYfwSeVBxuBH,iv:U22XpnO189TbazHIDMCkTs8pXW9crOsK6IO9dGNbsj8=,tag:fQn0bqdE6iSWv1Up5/vTuQ==,type:str]
    LOKI_USERNAME: ENC[AES256_GCM,data:+Wn3Ccto0w==,iv:pNNgPJyTdMFqksa28nVdiHRNSkuWyyxHu1MCJCAOmWI=,tag:SwTe/Q+Rz1w60Y+WtjuU9A==,type:str]
    LOKI_PASSWORD: ENC[AES256_GCM,data:3VmMskRP3DXU/ct8AZWsGOyAaJH2e5VCqpVHIPckF2eN2sdvWuqToUUuJJtt2JCR46a3rIWgeYqFoyv0AHHxBAlIBvCCzIVdjvI5Lq0xz1LPKfPAkjsqK6NixbWzz5LoL3ulndcY5uFe6m2uXMbU0cZLMN/l0eZCLmdzSS7pDvBfEUFfa9AA3RsaBhhK5bjNjj65vkY2GJs3yb24BvG7+QKRmVI=,iv:JAg09bHwKJT3y5ePbD/ZCUu4RPACgGpIPaKCQ7DoKmg=,tag:jcNWJNTI88O6bZp775gfVw==,type:str]
metadata:
    name: secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15cm9jgzm2w94fsf7kuk7cv68nmdgeha2wpynu5qrmmsdqsy45yaqdja4qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcXJDL3ppUzJWWGZBT0t0
            VmgrT29DSmdrNHdIdXFtdkxFaWFEOFFXVHpBCkZEUURJZVpRWEVxSkpsR0R0eFpB
            VHVyOGJHcUNHRTVSOTNIOGd2cWM4Z00KLS0tIEV2VlJ1RW10eWJSZ1UvajVJaWVD
            bkZLUmRBSGNidTNwS2RjSEV6NFhNdnMKp0JMBVDsndxZpxA1MxRWMth8lTVxanQ1
            NgNPEUeT/OLtqltCJmzgXumGVkGYniwnAaP+fEAmjxUWhDklG1ISNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T01:18:34Z"
    mac: ENC[AES256_GCM,data:30LRqvGeCni5RB/XiY4O8GxlFaiVLVs2bToQb+64hjFnX82HreQY2wfozNAISV6zOlq53eNN6CbAuKuVtLgfJ/rM/TfXpgi1gip1vMj9ihEIUgPDZlvkfJfXllx3a8pCciZRFIOWNvc5f4ThVP2MLQcfOPt601X1ICbXzAe/dEY=,iv:imDB+mdDpDo5yu4WtygvREr0NxfEonZ5ng6y9ig7ubY=,tag:7W/R5p0LluGv7P+0NYWEaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
