apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbor
spec:
  selector:
    matchLabels:
      app: thumbor
  template:
    metadata:
      labels:
        app: thumbor
    spec:
      containers:
        - name: thumbor
          image: ghcr.io/minimalcompact/thumbor
          env:
            - name: THUMBOR_PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
