apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbor
spec:
  selector:
    matchLabels:
      app: thumbor
  template:
    metadata:
      labels:
        app: thumbor
    spec:
      containers:
        - name: thumbor
          image: ghcr.io/minimalcompact/thumbor
          env:
            - name: THUMBOR_PORT
              value: "80"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 80
