apiVersion: apps/v1
kind: Deployment
metadata:
  name: bracket
spec:
  selector:
    matchLabels:
      app: bracket
  template:
    metadata:
      labels:
        app: bracket
    spec:
      containers:
        - name: bracket
          image: ghcr.io/danielpower/bracket:main@sha256:5ace06a39e6450d5c38034e46bccf09a55a10a1b0539261fdb457d28b3536e4d
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 8080
