version: "3"
services:
  reverse-proxy:
    image: traefik:v2.6
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.resolver.acme.email=me@danielpower.ca"
      - "--certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    privileged: true
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: --interval 300
    privileged: true
  personal-site:
    image: ghcr.io/danielpower/personal-site:main
    restart: always
    environment:
      PUBLIC_ORIGIN: https://www.danielpower.ca
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.danielpower.rule=Host(`danielpower.ca`, `www.danielpower.ca`)"
      - "traefik.http.routers.danielpower.entrypoints=websecure"
      - "traefik.http.routers.danielpower.tls.certresolver=resolver"
      - "traefik.http.routers.danpower.rule=Host(`danpower.ca`, `www.danpower.ca`)"
      - "traefik.http.routers.danpower.entrypoints=websecure"
      - "traefik.http.routers.danpower.tls.certresolver=resolver"
      - "traefik.http.routers.gulchnexus.rule=Host(`gulch.nexus`, `www.gulch.nexus`)"
      - "traefik.http.routers.gulchnexus.entrypoints=websecure"
      - "traefik.http.routers.gulchnexus.tls.certresolver=resolver"
  keeb-pro:
    image: registry.gitlab.com/danielpower/keeb-pro:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keeb.rule=Host(`keeb.danielpower.ca`)"
      - "traefik.http.routers.keeb.entrypoints=websecure"
      - "traefik.http.routers.keeb.tls.certresolver=resolver"
  rat:
    image: ghcr.io/danielpower/thetaverncellar:master
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rat.rule=Host(`rat.danielpower.ca`)"
      - "traefik.http.routers.rat.entrypoints=websecure"
      - "traefik.http.routers.rat.tls.certresolver=resolver"
  twat-bot:
    image: ghcr.io/danielpower/twat-bot:main
    restart: always
    env_file: /mnt/persistence/twat_bot.env
    environment:
      DATABASE_URL: sqlite://db.sqlite3
    volumes:
      - /mnt/persistence/twat-bot:/data:z
  rainbot-sands:
    image: ghcr.io/danielpower/rainbot-sands:main
    restart: always
    env_file: /mnt/persistence/rainbot_sands.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rainbot.rule=Host(`rainbot.danielpower.ca`)"
      - "traefik.http.routers.rainbot.entrypoints=websecure"
      - "traefik.http.routers.rainbot.tls.certresolver=resolver"
  swift-spider:
    image: ghcr.io/danielpower/swift-spider:main
    restart: always
    volumes:
      - /mnt/persistence/swift-spider:/data:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swift-spider.rule=Host(`journal.danielpower.ca`)"
      - "traefik.http.routers.swift-spider.entrypoints=websecure"
      - "traefik.http.routers.swift-spider.tls.certresolver=resolver"
