apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeb
spec:
  selector:
    matchLabels:
      app: keeb
  template:
    metadata:
      labels:
        app: keeb
    spec:
      containers:
        - name: keeb
          image: registry.gitlab.com/danielpower/keeb-pro:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 80
