apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:version-4.0.14.2939
          ports:
            - name: http
              containerPort: 8989
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /data/downloads
            - name: shows
              mountPath: /data/shows
      volumes:
        - name: downloads
          nfs:
            server: 192.168.0.2
            path: /main/downloads
            readOnly: false
        - name: shows
          nfs:
            server: 192.168.0.2
            path: /main/media/shows
            readOnly: false
        - name: config
          persistentVolumeClaim:
            claimName: config
