services:
    personal-site:
        image: ghcr.io/danielpower/personal-site:main@sha256:89faae6d74d5c47bc6442167677dfaa5921eb2357b6d94182b985dc94d150cfa
        container_name: personal-site
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.personal-site.rule=Host(`danielpower.ca`)"
            - "traefik.http.routers.personal-site.entrypoints=websecure"
            - "traefik.http.routers.personal-site.tls.certresolver=danielpowerca"
            - "traefik.http.routers.personal-site.middlewares=compression@file"
            - "traefik.http.routers.personal-site-www.rule=Host(`www.danielpower.ca`)"
            - "traefik.http.routers.personal-site-www.entrypoints=websecure"
            - "traefik.http.routers.personal-site-www.tls.certresolver=danielpowerca"
            - "traefik.http.routers.personal-site-www.middlewares=compression@file"
        restart: unless-stopped
        networks:
            - proxy
networks:
    proxy:
        external: true
