apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: personal-site
spec:
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
        - name: personal-site
          image: ghcr.io/danielpower/personal-site:main@sha256:49b4fa241beb4f9666624944ed7db97ee46aa67d3613decbfeb8aff504306df8
          imagePullPolicy: Always
          env:
            - name: PUBLIC_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PUBLIC_PROMETHEUS_URL
              value: http://prometheus-kube-prometheus-prometheus.svc.cluster.local:9090
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 3000
