apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-corn
spec:
  selector:
    matchLabels:
      app: stock-corn
  template:
    metadata:
      labels:
        app: stock-corn
    spec:
      containers:
        - name: stock-corn
          image: ghcr.io/danielpower/stock-corn:master@sha256:ba868ec3bcc7ef6da427d8d40bf751823ff7335dc032e72831c4ef3865fcbd67
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: DATABASE_PATH
              value: /data/db.sqlite
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: stock-corn
