apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-corn
spec:
  selector:
    matchLabels:
      app: stock-corn
  template:
    metadata:
      labels:
        app: stock-corn
    spec:
      containers:
        - name: stock-corn
          image: ghcr.io/danielpower/stock-corn:master@sha256:1ab1bbf6cf3f015b67d475407b95236267f59dde8c091b0127328b7c84d4f34f
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: DATABASE_PATH
              value: /data/db.sqlite
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: stock-corn
