apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-corn
spec:
  selector:
    matchLabels:
      app: stock-corn
  template:
    metadata:
      labels:
        app: stock-corn
    spec:
      containers:
        - name: stock-corn
          image: ghcr.io/danielpower/stock-corn:main
          envFrom:
            - secretRef:
                name: secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
