apiVersion: v1
kind: Secret
stringData:
    DISCORD_APPLICATION_ID: ENC[AES256_GCM,data:SqFye8McWHQW+plWhOV5WUc7Mw==,iv:a5UbpbBrRiJgoVpotwhLnAxrlmUO9Omi86dhMK+dsWA=,tag:xus5LzWEi+w1PE6ANvOOIg==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:tpK+TspW/4IPAdgPGTFuxgU9UpTGqLa0UqoE45/+uZRsnUSISzCjmD0knKkzfDexvKmDsokFYJpROAF8HWdX8Bj0bjDF1dz6,iv:v9a1uPP4qYbi+PXAqSQomvlO6sj2T3Dt/6X12oraiD8=,tag:xnhl8VBg5PYrH1p33MjHyA==,type:str]
    CORN_CZAR_ID: ENC[AES256_GCM,data:JXUijL86GsnXl/ZzOS/Br5VT,iv:UGf4GNEPEiZ7mMeoEuGzTe29SVQ1m9pe9QaW2pHt5ao=,tag:W5hZnQraDWwr5ZkxjxNQmw==,type:str]
metadata:
    name: secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15cm9jgzm2w94fsf7kuk7cv68nmdgeha2wpynu5qrmmsdqsy45yaqdja4qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ25PYzZQaGhFNmFpeEZm
            YWg2dFY4SkladFhQZWZsSkx5SEJPMUlmbjNBCjlodCtCLzRCYkRaU0ZoUHFCZ0VS
            Q2FYNzdFRGh1aXRiTEs3S0E4cGlyZmcKLS0tICsyYldoVGxpNGpQRk1HajRSdnNW
            RlVKSEFoZWFIbk5IVXlNR3dkejNNUGsKch8xu1RuTHSjtnCk2Ex+o2RFCVe6IvMg
            R1+NZQmobFwSSlPIQ5oSOobGMs3XgmDZF+ljl3vjlbUD+L2jqT9uvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T17:59:32Z"
    mac: ENC[AES256_GCM,data:4tX/RHpwAWILInt4q/alMhxDxYGKgqThZyS0QbhQuujfq8rQWSp87ysWIPCcXPpNWDmbbCFZgno6xKmncLWlPZ4uhjwGgWG1N8QCpxg8MFAPrtur3Dep7J8X8KFzwXAvtIEL6FITdITkpToxhJFhEhLUUQzmTAepfg8SuG2IVz4=,iv:a9O6qtX17BC222bdRH7btvlm9PLexLdmGQ0uavxqGVE=,tag:LzskvAA4fDL17Pi97G7nYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
