apiVersion: v1
kind: Secret
stringData:
    DISCORD_APPLICATION_ID: ENC[AES256_GCM,data:+9jObgDhT6NnvHOJstIE0R/HeQ==,iv:hYnuv4FV34FxZ7hcgDS36/T5ODjtbcVoE35r6OKetbs=,tag:I5wPNvCcCJoTJE1TGoBJJg==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:82D2z5lqGTqvdEgN9TZomqsvv5wKyVV7AKfVOqLM+Nydk7NEOEzn4BK0bdmMuWGaR295nR6ZWAUVnjx/BTMDZXcsIoGjSCp/,iv:YA9CGtpPZFzC4q18bMYAHIF9l5cFhc5y+oyR/dDmiIU=,tag:Q9VWrpoS1Chw7OTEPdlv5w==,type:str]
metadata:
    name: secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15cm9jgzm2w94fsf7kuk7cv68nmdgeha2wpynu5qrmmsdqsy45yaqdja4qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZN2JYZFgxVDdWZ1oxM241
            UGJkcVBJRWlEY0RMTDQ1QVNjSDQwYmpkaXlFCjB6bm45enFoM2RyRHQydTF5clh0
            VEdvdU5xNlQ5bHJSenVKeFJBMmN3d1kKLS0tIGkxcGR0eG1lRWFSWTB3d3RwTDBm
            MC91VGxJc2ZjWGhPcjRvRkpZa1B3eTAKZnpElDinOGLlaT3A08eBKFySzzrfd0/v
            DMg4VQAe/H6vm3G43jirt9/bvNRhozH2o0Ly6zOddHsdqdWS7ge8fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-22T05:04:11Z"
    mac: ENC[AES256_GCM,data:WOBhmNnO58JdCLa6jvBT8OWgDQ25UEboKaRX4X0oVdq5j3qeFQAhFQDnAUAnD3sNrE/AeaIdMHVCBVU2msr0Shtq1otuoI2bdhOOgswLR/mEINsiuRfQnyWtzKBSvUQzaVYEP3ZdVkkVx3/x7kbNyMEAmrVQJQINEROpc06BaTQ=,iv:FQVbNcOpt5rcFGvgKPYXwrDk9m/6/Rz8j0uoPlpR1uA=,tag:81C8jJNfrD/PUPxAU9rhYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
