apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  clusterIP: None
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8123
