apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8123
