services:
    app:
        image: ghcr.io/danielpower/osu-observer:main
        container_name: app
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.osuobserver.rule=Host(`osu.observer`)"
            - "traefik.http.routers.osuobserver.entrypoints=websecure"
            - "traefik.http.routers.osuobserver.tls.certresolver=osuobserver"
            - "traefik.http.routers.osuobserver.middlewares=compression@file"
        restart: unless-stopped
        networks:
            - backend
            - proxy
        environment:
            OSU_CLIENT_ID: ${OSU_CLIENT_ID}
            OSU_CLIENT_SECRET: ${OSU_CLIENT_SECRET}
            SAVE_MEDIA_PATH: "/media"
            RUN_MIGRATIONS: "true"
            DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@database:5432/postgres"
            SERVE_MEDIA_PATH: "https://assets.osu.observer"
            COOKIE_SECRET: ${COOKIE_SECRET}
            AUTH_REDIRECT_URI: "https://osu.observer/api/auth/callback"
            FRONTEND_URL: "https://osu.observer"
        volumes:
            - /nas/main/lab/osu-observer:/media
    database:
        image: postgres:18
        container_name: database
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
            - backend
        volumes:
            - /nas/main/lab/osu-observer-database:/var/lib/postgresql/18/docker
    assets:
        image: nginx
        container_name: assets
        restart: unless-stopped
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.observer-assets.rule=Host(`assets.osu.observer`)"
            - "traefik.http.routers.observer-assets.entrypoints=websecure"
            - "traefik.http.routers.observer-assets.tls.certresolver=osuobserver"
            - "traefik.http.routers.observer-assets.middlewares=compression@file"
        volumes:
            - /nas/main/lab/osu-observer:/usr/share/nginx/html:ro
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
networks:
    proxy:
        external: true
    backend:
        internal: true
