apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 71.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community