apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 71.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
    prometheusOperator:
      admissionWebhook:
        certManager:
          enabled: true
    kubelet:
      enabled: true