apiVersion: v1
kind: Secret
metadata:
    name: config-cloudflare-ddns
stringData:
    config.yml: ENC[AES256_GCM,data:ARc6NSTPw+mWeLNsxBlYkh4fKaKSiKIlbeRoizchs6Loanc9AYQeuy6eqaORbSi8vLuWhLAI2QLMBay99mJt5H+EVRXzckor6UnBA8/4YzuJ29aU6wy1EnkGXtmXqUCUbdS5bGtAi4GSZpiIgsSTYERi2swPaH+7cTk0wMCBVkXzkCdpeg2qvXLbHxc7Wt5UKh99ljinC2Usj4wZy4cWfcn4ps47Vx0pS6qtJQRMLuZ0NHbH+5hQcUrctTVKgedVFs+j5LVSqkITbukWy/ZEixIu6aydFeseVNkgfaBSMBLdSaBdi1OCRjHA92HPLqow2qyx8aZAu/Nn8F5jhLMsK3ff4sYNDGCW5gwF4rQOrBjDT51hH0KdgwrQi44ZvAuvMDKVYaNxpnrlQW7Ppj7fqTPdC6lPoZQQLv7y04GEv3fWC9zunryqUBD5RKDq8syg2jqKtpQDxG1u8gJc0tYpiFpu5B9e+tCy5rMwzXRRB3sU2Gltfov+pZSSZUynCqLnqEu0dcmg4f/ZBEuN9wN5Fg7WHgT+CKkfmnEJwjjmo1rfEGIU4dsOz82fLa3IRNXDG477VTeYh+rYdIcDTlaWdPHbMoG/xx5abMxWcMRBrEl0fUysN+clCLpoAenh7x+PlTN0ox6TQXecswqwmrBljE9Wg+3uGNY=,iv:B8/v/gGpTko9vkMmY5r6JMAIW4ZtS5f+cX0AJ4TWbeE=,tag:ROS/ryuoM/qAvovKxSrvrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15cm9jgzm2w94fsf7kuk7cv68nmdgeha2wpynu5qrmmsdqsy45yaqdja4qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbkVjZkt6M1J1MnlrNCtZ
            NkRxUDJxQ0Q4T1RVcE1ha0U0UmZlVitLR2dZClh1eTU3UEN2OUVOeWh2NXN0VlBu
            VzJlem1LV01iK2F5TkJ3THM3TW1SNG8KLS0tIHBoRVVvdzRwQzNKUzdSQUtGOXBh
            MEZ6dVJGVWt3bEQ1aHBQQ2dDbzhUNEUKJQmYZDdXtypgVtZzHgfo8OqyWwinq5gG
            jzae8sNidi9bhoYHyC8F23zW/pYqH0AjdoMXsEXo56PV8RQuBI8Tog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-28T23:06:48Z"
    mac: ENC[AES256_GCM,data:lfkq6KNA7d90ct4V1fJSJm51dm8KYAJoJWXmpbHL1u9TWMPnDvYsOR7snf9rjk0KV0iK6OZgd4kdrV4S72sHdr/6G+XsBjxtijhYs3PILCMZZhajp70NWikvg6AWeBCKRGeduQ0iemt9Fn2xldrcClWGcB4kbhBs3l2c7q1ZZyA=,iv:jHIDlrFuu99d4AYE2/8WXZME2fhwI6Qk0J3KIOVZzDw=,tag:8pIHhMejngzpFargDj49hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
