apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: moby
  namespace: flux-system
spec:
  interval: 1h0m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "flux/infrastructure/moby"
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
