apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
          ports:
            - name: http
              containerPort: 8191
