apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/flaresolverr:latest
          ports:
            - name: http
              containerPort: 8191
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
