apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainbot-sands
spec:
  selector:
    matchLabels:
      app: rainbot-sands
  template:
    metadata:
      labels:
        app: rainbot-sands
    spec:
      containers:
        - name: rainbot-sands
          image: ghcr.io/danielpower/rainbot-sands:main@sha256:789f60463d8164344602b2b1131bd4a2b25a96d7ad7ff8acc951d4c97041603b
          envFrom:
            - secretRef:
                name: secrets
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
