apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainbot-sands
spec:
  selector:
    matchLabels:
      app: rainbot-sands
  template:
    metadata:
      labels:
        app: rainbot-sands
    spec:
      containers:
        - name: rainbot-sands
          image: ghcr.io/danielpower/rainbot-sands:main
          envFrom:
            - secretRef:
                name: secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
