apiVersion: v1
kind: Secret
stringData:
    DISCORD_APPLICATION_ID: ENC[AES256_GCM,data:zoLO0EziPJZZe6EgblKMC2/83A==,iv:wMWWVz6XWBmmui7AFn8bhmUdnOi5Br+sg3DFfDy/qwk=,tag:09kgv8TRrCnfezySkntJbQ==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:olQAVR9nu5wd2Bjp7j11uG4qE4hW0nvtt02J+QW0W7py9BZFdOJHvouIzXHy5bKLMuyG6LF8T/EybgwVCU0sFKlJEBBYn7MV,iv:Z4GaRxSVJvTPd687T0bb2/Lvi/czTGmZN41m/yHEaio=,tag:Brl4YQ3D9YzJNtMpptqzDw==,type:str]
    DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:NNhaU4ZcGp7Owu5EzMfLTm3E,iv:8ek/etRg1mAPNV1rjA5yjnUxIX6CnPGCdYXIwSb+M3Q=,tag:NnpPPZvZ3K9pkorVss/XZw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ogqQUad1X6Sr+SHDbwQr,iv:Q+JLCZ+3h3iRjExCOaXnGH87FZE1EwuPUhm4yTOzO2g=,tag:DKVYOWA/V15xy1idtaTY1w==,type:str]
    SCHEDULE: ENC[AES256_GCM,data:4WtO8qCajlkdcw==,iv:L7WJOmMKuL7B9RpDfRh/vbpK2IqswwWWCqpCAznr+WE=,tag:3O3QRbAgkD0nXiKZq1vntg==,type:str]
    QUEST_SCHEDULE: ENC[AES256_GCM,data:o0x/cT0r2cbx+w==,iv:NMCl/S+yLbFu0ubXCdMKxTdHIQ5qtEiqbBx8YcPLxOM=,tag:cVlHT/ryCZ4cub4/X9F6DQ==,type:str]
metadata:
    name: secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15cm9jgzm2w94fsf7kuk7cv68nmdgeha2wpynu5qrmmsdqsy45yaqdja4qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSTFkSzB0aHBtVTJiQ0RM
            Z0UrYkZBME5vNGg2THVmNUhOaUVkVm5YaWlJCjJNYnZWWUpteTk3a3Y0WkRGQjl5
            S3dYVUtqRFhEY3d1a2l5Z1JQTjh0eTAKLS0tIEExM1Y3Ryt6VjlVMVUxUEJUZlhP
            QlkrN3crV3ZaUWRFV1R6b1ZjVUJESlkKvGLcFUC7Yo7Va8HQYJO0kbUbvxxyV8o7
            0RdPQINnxDr5W9kAy2DVlnkzdHXd+zhATyQ/NdftsJBWMmccPONu7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T02:17:02Z"
    mac: ENC[AES256_GCM,data:T8P5CHgAU8UuzdooA77k64dUmrUZFI5fngQtWV83+l3ANuiLrVGyMLVc7pTCHfgdKvyvBVoFzH6uJuNFksBQD7At0W3OqCuFw9fQ6hMbp9/F+KOG5oWTcI3SA/zS2FLBH2Wm/m0PQY0WGcFfVW/3O8UEe3oPvJ61AaQEmerZHH4=,iv:YwGh8OhShMw684m0IwwQyjzdJevh6jfD3V7i7tJJVP8=,tag:jOB2iuxBpRNCWGcxQjoJgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
