apiVersion: v1
kind: Secret
stringData:
    DISCORD_APPLICATION_ID: ENC[AES256_GCM,data:LYGlsA2EaOvVwwbab9y7XKq34w==,iv:o6aIVfvFjEEnWB8Xz80vKsASPE0WuSMX9hsIirN8cPo=,tag:00pm8fvShUBUhHpLoM9+YA==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:oW1lrPhVQRlRfN4wPTp6GdklJIMkzBI7nUI+z5ah9rq7/B5v+8tknnvBIgZb4OlutrpqKTo7374+Gr+b4No4QareNAIy6pWT,iv:2XrFHfDnkdboPG17TDKoLAAF0q6Lb3dzKDNHH/vsw1A=,tag:3Y28Sk3TMFk4tX102SLNxg==,type:str]
    DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:V5z94dol+zkEutN0BbpAI1Eu,iv:E90nPklJvUkzID09Kbu1Bgn5JIdXmB1cY6Sr4RLDeLw=,tag:BhcLkiIK6li5VrEeayhWdA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:M+jvkxM3hkmeoR8jpwqt,iv:S2ve0k/BnwnZip2tFDgC+nplxmsXbi2HpllplDaZPQM=,tag:BCi6yJJ84Z8XS4NL2blaEQ==,type:str]
    SCHEDULE: ENC[AES256_GCM,data:kZB1K74TVj88k4c=,iv:I/eFPGwe9U6JOz35G7TGSm7TnrR01g72EO1t5fhix4k=,tag:aHmBV43+t/wk7y4CY2/1xw==,type:str]
    QUEST_SCHEDULE: ENC[AES256_GCM,data:DQL0xIK8rD9zXZQ=,iv:SgSXzTvveOy1DMzJ5rvrVkp8tMBuZ0rg3tMrSKIIj+0=,tag:6xuHfToUKBrzHsx3GdI6tw==,type:str]
    TZ: ENC[AES256_GCM,data:85DpR1f6Zd7kgiZKMGXvhg==,iv:/eNqOWnybikEdmDOJ4sUGoMxPee4ov2zKuiGM6aSZEA=,tag:sx4Ib+a3zDt1ALBWsrqrFw==,type:str]
metadata:
    name: secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15cm9jgzm2w94fsf7kuk7cv68nmdgeha2wpynu5qrmmsdqsy45yaqdja4qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcDZkWDVVTXVhOEJmS3RL
            UkpwR0k3QWZSSGRuWDBXWnNkSXVFdlhIalJJCmdUaGsxbjJFUVpyTDc4K0piek5s
            NEd2Q2o4RDJpdVRzSUEwVUdkSXUzM1UKLS0tIGg5a2tBc2lqUVJ3Zm1WUVlDcnNn
            QlE3aFZaQkpsWDlYanZxKzNqeWdHT2cKWBEMay21ciNReya198Yz5vV+fjJ+PebE
            ZTKMH0Q7Q+5LfWfOLAxlQxjuQnbuxSowUM03tyGghFxLcs5FkNiigA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T17:15:29Z"
    mac: ENC[AES256_GCM,data:MC7lYaBYO34dcJlga4OqEpsmk/pBcf1sZiRlWRf7na3SupOt0KoZNMPIadC3RG81eyvoQsJA0LRPmyGGBcoRSyd1Y2fJwt9m62926JHRYc/HgpsmLNXCLo+x1M2vR541bzGxUOrcE6MnsdVLwg1r789IEH/UpzklFCoDwopP5ls=,iv:aEgi+JbSddTx3FdjeEctOC18ewv16dcjeZyJVDCt8u8=,tag:kN+PblWEiylkXCagF/a/kA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
