apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - name: http
              containerPort: 7878
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /data/downloads
            - name: movies
              mountPath: /data/movies
      volumes:
        - name: downloads
          nfs:
            server: 192.168.0.2
            path: /main/downloads
            readOnly: false
        - name: movies
          nfs:
            server: 192.168.0.2
            path: /main/media/movies
            readOnly: false
        - name: config
          persistentVolumeClaim:
            claimName: config
