apiVersion: v1
kind: Service
metadata:
  name: radarr
  annotations:
    tailscale.com/hostname: radarr
spec:
  selector:
    app: radarr
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
