apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  annotations:
    tailscale.com/hostname: prowlarr
spec:
  selector:
    app: prowlarr
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
