apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twatbot
secretGenerator:
  - name: twatbot-secrets
    envs:
      - .env.secret
resources:
  - namespace.yaml
  - deployment.yaml
