apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - name: http
              containerPort: 8096
            - containerPort: 8920
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies
              mountPath: /data/movies
            - name: shows
              mountPath: /data/shows
            - name: music
              mountPath: /data/music
            - name: youtube
              mountPath: /data/youtube
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: movies
          persistentVolumeClaim:
            claimName: movies
        - name: shows
          persistentVolumeClaim:
            claimName: shows
        - name: music
          persistentVolumeClaim:
            claimName: music
        - name: youtube
          persistentVolumeClaim:
            claimName: youtube
