apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - persistent-volume-claim-data.yaml
  - persistent-volume-claim-music.yaml
  - persistent-volume-claim-movies.yaml
  - persistent-volume-claim-shows.yaml
  - persistent-volume-claim-youtube.yaml
