apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube
  path: youtube
spec:
  storageClassName: nfs-csi-root
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
