apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shows
  path: shows
spec:
  storageClassName: nfs-csi-root
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
