apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  path: music
spec:
  storageClassName: nfs-csi-root
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
