apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-grafana
  sessionAffinity: None
