apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  releaseName: prometheus
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 69.5.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    grafana:
      enabled: false
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-csi
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
