apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeb-pro
spec:
  selector:
    matchLabels:
      app: keeb-pro
  template:
    metadata:
      labels:
        app: keeb-pro
    spec:
      containers:
        - name: keeb-pro
          image: ghcr.io/danielpower/keeb-pro:master@sha256:619daf1421decce0a5dfc5dedc8d7d7fe21f839083d29156fbf01c89d20109dd
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 8080
