apiVersion: v1
kind: Secret
metadata:
    name: config-cloudflare-ddns
stringData:
    config.json: ENC[AES256_GCM,data:hcfEDHCoCzNclfoe2kD4XvWqYMj2WQsC6/S9UREZt2FHeg0sRGs1JdcamwBiMLtAsD4fyokaAGvPeH/dT0+K6JOI/H/lZXTzDV3H+b69fikCzlgbwuzefU0KdoY5gcUtBRyBgBEWJ+JPfu77s984+RyiR/5egx7YfylNYfiX4Psd8Gmcvr6UBuneZVhCC5TgPKXSVHKUWqpHQPiT3/t+WBP12/6LU4vDqLW/7KXGYAXKW+w0Q4E63g5qJgRR1xmoI7AfRVPXgZRye6wv+Jyu3H/tE09EH46tyjR2qF4tpIiZuxfbDSZF5WCdPzfDkwIxCgaMaJGbulDePu9fjZ/3hUTOuEA/jghvoD7wm/4KHVA+zC6PQNUf5peNYH4Aok1h8Qhb0j/uzI2ltq0+JhGKO4lKyHEEfyZ0xCpETfwaouB30+onAoDgdR0s9kfLzAA0t+3azv79AgQEQrtMDfe2vOj16d8D1K4oJLJlQsfOszsNKAZroXSb+XYcNuQhdfHGr6bNt0D6VXPLjo68ejWB+6hALOSLeS1ONRl763d9ivuf0sCmocbsyRc9MTWpYVy4Y7L2rwx0fCeX8wGsF+vKkAsEfUIdVgu7/5ACieC6qfrHiUqAPEKS6gf3I4HNBwp/JRRA3iZWfjazzhA98JxNj8aSwm/SZ+2kIMwbrYWk+2wThUdCvqhZKuncCNs7bBXrrPe7fsNUEU2QjGmFWHwZu1OXYqaR0WEkGPKp51M0MNaozaZJyb1YF4vtGECutA==,iv:hu6dX2WPbLiE9iW+xPuAX71UzDiLEpO2dvNcH93IN00=,tag:um0Sl7UAgKMGyQTUoXHEGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15cm9jgzm2w94fsf7kuk7cv68nmdgeha2wpynu5qrmmsdqsy45yaqdja4qh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eDdrUWNNMU05NGlONEhw
            Q3hmSnQrMXVwMGFMNDdaWFBLNWJmR0hyWFd3CmYwV0NjRTJXdHM2aHh5S3JqVVo3
            dVBRa29JcEtZSWFGTVBKMGliNStxRVEKLS0tIFVwR3BvMko2clFGaDhUMGxQT1dP
            T29qaXV3Q3pBOTBGdE9uTDBHN251aTAK1rA1m2Wh9eXeLdK+maWrSbzDFuykP61Q
            3f7t7Np9zYEx4VMoSYagqrDrkUoHp0dUzgjAVEkFq4o/gfIuBV8xSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T05:52:40Z"
    mac: ENC[AES256_GCM,data:BRYnCbIzSlSE/4V324AobXFIViFny9ftsZ2EoyJybw603oBmJyyAAc5nHki9KJCZS1pbpDRd8FAQ7dTj5K8QtJky0y024sfZQucq2thrznp2eZ3YaO5cuGw3AiwiBHnO/xgoq3aY4q4s4HhwkIcG5FD3J3xOI9uD/KbcwW1pA8c=,iv:zjbPIGFq7ij3YPkXZU4sJV5ajTRbx2i2eaB1IYg9Jx0=,tag:CLBIcfgiLiov1a3PyYcVTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
