apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  releaseName: csi-driver-nfs
  interval: 1h
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.7.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: kube-system
