apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-public-proxy-config
data:
  config.yaml: |
    prometheus:
      url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
      queries:
        health:
          query: up
          interval: 1000
        kube_node_info:
          query: kube_node_info
          interval: 1000
        ready_nodes:
          query: kube_node_status_condition{condition="Ready",status="true"}
          interval: 1000
