apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-public-proxy
spec:
  selector:
    matchLabels:
      app: prometheus-public-proxy
  template:
    metadata:
      labels:
        app: prometheus-public-proxy
    spec:
      containers:
        - name: prometheus-public-proxy
          env:
            - name: CONFIG_PATH
              value: /config/config.yaml
          image: ghcr.io/danielpower/prometheus-proxy:master@sha256:0c9ae5b4cde2c6c9ee61650a0c869f993fd72b833c84fce411b49b715c76fe03
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-public-proxy-config
