apiVersion: apps/v1
kind: Deployment
metadata:
  name: osu-replay-viewer
spec:
  selector:
    matchLabels:
      app: osu-replay-viewer
  template:
    metadata:
      labels:
        app: osu-replay-viewer
    spec:
      containers:
        - name: osu-replay-viewer
          image: ghcr.io/danielpower/osu-web-replay-viewer:main@sha256:7928e64862a971198901ec553bd6fed0c623d80c0017761e6b01fa0c3e2e824a
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              containerPort: 3000
